site_name: 0bsNetwork Developer Site
nav:
    - Home: index.md
    - About 0bsNetwork: about.md
    - Components and Services: componentsandservices.md
    - Transactions: transactions.md
    - Smart Contracts: smartcontracts.md
    - Full Node Operation: fullnode.md
    - Full Node REST API: nodeapi.md
    - Javascript Libraries: javascript.md
    - React Library: react.md
    - Java Library: java.md
    - Python Library: python.md
    - C# Library: cs.md
    - Data Service API: dataservice.md
    - 0bsLink: link.md
    - Tutorials: tutorials.md
    - Glossary: glossary.md
theme: readthedocs
extra_css:
  - 'stylesheets/extra.css'